name: Test

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get package.json version
        id: get_version
        shell: bash
#        run: echo "PACKAGE_VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV
        #run: echo 'PACKAGE_VERSION=$(node -p "require(\"./package.json\").version")' >> $GITHUB_ENV
        run: echo "PACKAGE_VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
      - name: Print env
        shell: bash
        run: echo $PACKAGE_VERSION
